[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.0"

[[override]]
  branch = "master"
  name = "github.com/dudk/phono"

[[constraint]]
  branch = "master"
  name = "github.com/dudk/phono"

[prune]
  go-tests = true
  unused-packages = true
